import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useState, useEffect } from "react";

export default function Home() {   
  const [userName, setUserName] = useState("");
  const [filtteriValinta, setFiltteriValinta] = useState("");

  const kanaRuoat = ["kanajauhelihakastike", "nachovuoka kana", "couscous lihalla", "kanan jauhelihakeitto"];
  const kasvisRuoat = ["Kukkakaaliparsakaali gratiini", "Kasvis couscous", "linssikeitto", "kesäkeitto"];
  const porsasRuoat = ["jauhelihakastike", "nachovuoka", "couscous lihalla", "jauhelihakeitto"];
  const nautaRuoat = ["jauhelihakastike", "nachovuoka", "jauhelihakeitto"];
  const kalaRuoat = ["Uunikala", "paistettu kala", "kalakeitto"];

  useEffect(() => {
    fetch(`http://localhost:3000/api/userName`)
     .then((response) => response.json())
     .then((actualData) => setUserName(actualData.name.charAt(0).toUpperCase()+actualData.name.slice(1)));
   }, []);

   const [handleChange] = useState((tyyppi) => {
    return () => {
      console.log(tyyppi);
      setFiltteriValinta(tyyppi);
    };
  });
  
  function getRandomDish() {
      switch(filtteriValinta){
        case(1)://kana
          
          break;
        case(2)://kasvis

          break;
        case(3)://porsas

          break;
        case(4)://nauta

          break;
        case(5)://kala

          break;
        default:
          
          break;
      }
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>{userName}:n ruokaohje generaattori</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Ruokaohje generaattori
        </h1>

        

        <div className={styles.grid}>
          <div className={styles.card}>
            <button id='generateRecipe' className={styles.card}>Generoi ruokaohje</button>
            <select id="dishTypes" onChange={(value) => setFiltteriValinta(value.target.value)} value={filtteriValinta}>
              <option value="1">Kana</option>
              <option value="2">Kasvis</option>
              <option value="3">Porsas</option>
              <option value="4">Nauta</option>
              <option value="5">Kala</option>
            </select>
            <p>{filtteriValinta}</p>
          </div>
          

          <div className={styles.card}>

          </div>

          

        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://www.linkedin.com/in/samuli-lehtonen/"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by Sampan koodi
        </a>
      </footer>
    </div>
  )
}
